name: Bug Report
description: Report a bug in the coding assignment for the course. 
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help identify and fix the bug
  - type: textarea
    id: description
    attributes:
      label: Describe your issue
      placeholder: When I run the docker here this happens
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce (optional)
      placeholder: |
        1. Go to week 1 assignment folder
        2. Run langgraph dev
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Details about the environment
      placeholder: |
        1. Python version: 3.10
        2. Operating system: Windows
    validations:
      required: True
  - type: textarea
    id: screenshots
    attributes:
      label: Put here any screenshots or videos (optional)
  - type: dropdown
    id: assign
    attributes:
      label: "Are you blocked because of this?"
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue! We will get back to you as soon as possible.